resource_manifest_version "44febabe-d386-4d18-afbe-5e627f4af937"

files {
  'content/resident/collision.awc',
  'content/resident/collisions.awc',
  'content/resident/explosions.awc', 
  'content/resident/melee.awc',
  'content/resident/weapons.awc',
  'content/weapons_player/lmg_combat.awc',
  'content/weapons_player/lmg_mg_player.awc',
  'content/weapons_player/mgn_sml_am83_vera.awc',
  'content/weapons_player/mgn_sml_am83_verb.awc',
  'content/weapons_player/mgn_sml_sc__l.awc',
  'content/weapons_player/ptl_50cal.awc',
  'content/weapons_player/ptl_combat.awc',
  'content/weapons_player/ptl_pistol.awc',
  'content/weapons_player/ptl_px4.awc',
  'content/weapons_player/ptl_rubber.awc',
  'content/weapons_player/sht_bullpup.awc',
  'content/weapons_player/sht_pump.awc',
  'content/weapons_player/smg_micro.awc',
  'content/weapons_player/smg_smg.awc',
  'content/weapons_player/snp_heavy.awc',
  'content/weapons_player/snp_rifle.awc',
  'content/weapons_player/spl_grenade_player.awc',
  'content/weapons_player/spl_minigun_player.awc',
  'content/weapons_player/spl_prog_ar_player.awc',
  'content/weapons_player/spl_railgun.awc',
  'content/weapons_player/spl_rpg_player.awc',
  'content/weapons_player/spl_tank_player.awc',
  'content/db_shotgun.awc',
  'content/ptl_revolver.awc',
  'content/weaponbullpuprifle.meta',
  'content/weaponcombatpdw.meta',
  'content/weaponcompactrifle.meta',
  'content/weapongusenberg.meta',
  'content/weaponheavypistol.meta',
  'content/weaponmachinepistol.meta',
  'content/weaponmarksmanpistol.meta',
  'content/weaponmarksmanrifle.meta',
  'content/weaponminismg.meta',
  'content/weaponmusket.meta',
  'content/weaponrevolver.meta',
  'content/weapons.meta',
  'content/weapons_assaultrifle_mk2.meta',
  'content/weapons_bullpuprifle_mk2.meta',
  'content/weapons_carbinerifle_mk2.meta',
  'content/weapons_combatmg_mk2.meta',
  'content/weapons_doubleaction.meta',
  'content/weapons_heavysniper_mk2.meta',
  'content/weapons_marksmanrifle_mk2.meta',
  'content/weapons_pistol_mk2.meta',
  'content/weapons_pumpshotgun_mk2.meta',
  'content/weapons_revolver_mk2.meta',
  'content/weapons_smg_mk2.meta',
  'content/weapons_snspistol_mk2.meta',
  'content/weapons_specialcarbine_mk2.meta',
  'content/weaponsnspistol.meta',
  'content/weaponspecialcarbine.meta',
  'content/weaponvintagepistol.meta',
}

data_file 'AUDIO_WAVEPACK' 'content/resident'
data_file 'AUDIO_WAVEPACK' 'content/weapons_player'
data_file 'AUDIO_WAVEPACK' 'content'
data_file 'AUDIO_WAVEPACK' 'content/ptfx'
data_file 'AUDIO_WAVEPACK' 'content/ptfx_hi'
data_file 'AUDIO_WAVEPACK' 'content/ptfx_lo'